language: python

python:
  - "3.7-dev"

sudo: required

services:
  - docker

install:
  - pip install flake8 pipenv salt-pepper
  - pipenv install --deploy

script:
  - pipenv run lint
  - bash docker/build.sh
